import type { Metadata } from "next";
import "../globals.css";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (

        <div className="h-screen w-full flex gap-5 font-michroma bg-secondary text-primary-text">
          {children}
        </div>
  );
}
