import type { Metadata } from "next";
import { Geist, Geist_Mono, Michroma, Poppins, Montserrat} from "next/font/google";
import "./globals.css";
import Navabr from "@/components/Navabr";
import Footer from "@/components/Footer";

const michroma = Michroma({
  weight: "400",
  variable: "--font-michroma",
  subsets: ["latin"],
  display: 'swap',
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={` ${michroma.variable} ${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${montserrat.variable}  antialiased h-screen w-screen font-michroma`}
      >
        <div className="h-full w-full flex flex-col md:flex-row bg-primary text-secondary-text relative">
          <Navabr />
          <main className="h-screen w-full">
            {children}
          </main>
          <div className="absolute bottom-0 w-full">
            <Footer />
          </div>
        </div>

      </body>
    </html>
  );
}
